[theme]
base = "light"
primaryColor = "#1e91eb"
backgroundColor= "#349ced"
seconderyBackgroundColor = "#11598f"
textColor = "#0d0d0d"
borderColor = "#008497"
font = "Edu NSW ACT Hand Cursive"
headingFont = "Edu NSW ACT Hand Cursive"

baseRadius = ""
[[theme.fontFaces]]
family = "Edu NSW ACT Hand Cursive"
url = "https://fonts.google.com/specimen/Edu+NSW+ACT+Cursive?preview.script=Latn&query=cursive"
weight = 400
style = "normal"